name: CI - Parabank Testes CRUD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install ChromeDriver
      run: |
        webdrivermanager chrome --linkpath /usr/local/bin

    - name: Run Robot Framework tests
      run: |
        robot -d results tests/PB_web_tests.robot

    - name: Upload test results
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: robot-results
        path: results/
