name: CI - Parabank Testes CRUD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install robotframework-seleniumlibrary==4.9.0
        pip install robotframework-browser

    - name: Install browsers
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: 'latest'
        
    - name: Verify installations
      run: |
        google-chrome --version
        chromedriver --version
        python --version
        robot --version

    - name: Run Robot Framework tests
      run: |
        export ROBOT_OPTIONS="--variable BROWSER:headlesschrome --variable URL:https://parabank.parasoft.com/parabank/index.htm"
        robot $ROBOT_OPTIONS -d results tests/PB_web_tests.robot

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: robot-results
        path: results/
